### ISSUE TITLE
Missing 's' word in website documentation

### ISSUE THREAD

**Issue by wahyudies** [luangjokaj/fuzzymail#6]
Your website documentation at **CSS, PostCSS and Sass** section missing 's' word, causing error when run `npm run prod` if user just copy and paste without double check the code.

```javascript
function stylesProd() {
    return src('./src/assets/css/style.scss')
        .pipe(sass({includePaths: 'node_modules'}).on('error', sass.logError))
        .pipe(dest('./dist/assets/css'));
}
```
Instead

````javascript
function stylesProd() {
    return src('./src/assets/css/styles.scss')
        .pipe(sass({includePaths: 'node_modules'}).on('error', sass.logError))
        .pipe(dest('./dist/assets/css'));
}

**Comment by luangjokaj** [comment]
> Your website documentation at **CSS, PostCSS and Sass** section missing 's' word, causing error when run `npm run prod` if user just copy and paste without double check the code.
> 
> ```js
> function stylesProd() {
>     return src('./src/assets/css/style.scss')
>         .pipe(sass({includePaths: 'node_modules'}).on('error', sass.logError))
>         .pipe(dest('./dist/assets/css'));
> }
> ```
> 
> Instead
> 
> ```js
> function stylesProd() {
>     return src('./src/assets/css/styles.scss')
>         .pipe(sass({includePaths: 'node_modules'}).on('error', sass.logError))
>         .pipe(dest('./dist/assets/css'));
> }
> ```

Thanks for the heads-up. Just updated the docs.
